import type { Route } from "./types"

export const routes: Route[] = [
  {
    id: 1,
    from: "Kigali",
    to: "Musanze",
    price: 2500,
    routeType: "provincial",
    companyId: 1,
    availableSeats: 12,
    status: "departed",
    isCompleted: false,
    stops: [
      {
        name: "Kigali",
        estimatedArrival: "2024-01-15T08:00:00.000Z",
        isMidpoint: false,
        isPassed: true,
        price: 0,
      },
      {
        name: "Gakenke",
        isMidpoint: true,
        isPassed: false,
        price: 1800,
        estimatedTime: "12 min",
      },
      {
        name: "Musanze",
        isMidpoint: false,
        isPassed: false,
        price: 2500,
      },
    ],
    currentLocation: {
      nextStop: "Gakenke",
      remainingTime: "12 min",
      remainingDistance: "18 km",
      lastPassedStop: "Kigali",
      lastPassedTime: "2024-01-15T08:05:00.000Z",
    },
    carplate: "RAB 123A",
  },
  {
    id: 2,
    from: "Kigali",
    to: "Huye",
    price: 2000,
    routeType: "provincial",
    companyId: 2,
    availableSeats: 8,
    status: "scheduled",
    isCompleted: false,
    stops: [
      {
        name: "Kigali",
        estimatedArrival: "2024-01-15T09:30:00.000Z",
        isMidpoint: false,
        isPassed: false,
        price: 0,
      },
      {
        name: "Nyanza",
        isMidpoint: true,
        isPassed: false,
        price: 1200,
      },
      {
        name: "Huye",
        isMidpoint: false,
        isPassed: false,
        price: 2000,
      },
    ],
    currentLocation: null,
    carplate: "RAC 456B",
  },
  {
    id: 3,
    from: "Kigali",
    to: "Rubavu",
    price: 3000,
    routeType: "provincial",
    companyId: 3,
    availableSeats: 15,
    status: "scheduled",
    isCompleted: false,
    stops: [
      {
        name: "Kigali",
        estimatedArrival: "2024-01-15T10:00:00.000Z",
        isMidpoint: false,
        isPassed: false,
        price: 0,
      },
      {
        name: "Muhanga",
        isMidpoint: true,
        isPassed: false,
        price: 1000,
      },
      {
        name: "Karongi",
        isMidpoint: true,
        isPassed: false,
        price: 2200,
      },
      {
        name: "Rubavu",
        isMidpoint: false,
        isPassed: false,
        price: 3000,
      },
    ],
    currentLocation: null,
    carplate: "RAD 789C",
  },
  {
    id: 4,
    from: "Musanze",
    to: "Rubavu",
    price: 1500,
    routeType: "provincial",
    companyId: 4,
    availableSeats: 6,
    status: "departed",
    isCompleted: false,
    stops: [
      {
        name: "Musanze",
        estimatedArrival: "2024-01-15T11:15:00.000Z",
        isMidpoint: false,
        isPassed: true,
        price: 0,
      },
      {
        name: "Gakenke",
        isMidpoint: true,
        isPassed: true,
        passedTime: "2024-01-15T12:30:00.000Z",
        price: 800,
      },
      {
        name: "Rubavu",
        isMidpoint: false,
        isPassed: false,
        price: 1500,
        estimatedTime: "25 min",
      },
    ],
    currentLocation: {
      nextStop: "Rubavu",
      remainingTime: "25 min",
      remainingDistance: "32 km",
      lastPassedStop: "Gakenke",
      lastPassedTime: "2024-01-15T12:30:00.000Z",
    },
    carplate: "RAE 321D",
  },
  {
    id: 5,
    from: "Kigali City Center",
    to: "Kigali Airport",
    price: 800,
    routeType: "city",
    companyId: 5,
    availableSeats: 10,
    status: "scheduled",
    isCompleted: false,
    stops: [
      {
        name: "Kigali City Center",
        estimatedArrival: "2024-01-15T12:00:00.000Z",
        isMidpoint: false,
        isPassed: false,
        price: 0,
      },
      {
        name: "Kimisagara",
        isMidpoint: true,
        isPassed: false,
        price: 200,
      },
      {
        name: "Remera",
        isMidpoint: true,
        isPassed: false,
        price: 400,
      },
      {
        name: "Kigali Airport",
        isMidpoint: false,
        isPassed: false,
        price: 800,
      },
    ],
    currentLocation: null,
    carplate: "RAF 654E",
  },
  {
    id: 6,
    from: "Nyabugogo",
    to: "Kimironko",
    price: 500,
    routeType: "city",
    companyId: 6,
    availableSeats: 14,
    status: "departed",
    isCompleted: false,
    stops: [
      {
        name: "Nyabugogo",
        estimatedArrival: new Date("2024-01-15T14:00:00").toISOString(),
        isMidpoint: false,
        isPassed: true,
        price: 0,
      },
      {
        name: "City Center",
        isMidpoint: true,
        isPassed: true,
        passedTime: new Date("2024-01-15T14:10:00").toISOString(),
        price: 150,
      },
      {
        name: "Remera",
        isMidpoint: true,
        isPassed: false,
        price: 300,
        estimatedTime: "8 min",
      },
      {
        name: "Kimironko",
        isMidpoint: false,
        isPassed: false,
        price: 500,
        estimatedTime: "15 min",
      },
    ],
    currentLocation: {
      nextStop: "Remera",
      remainingTime: "8 min",
      remainingDistance: "5 km",
      lastPassedStop: "City Center",
      lastPassedTime: new Date("2024-01-15T14:10:00").toISOString(),
    },
    carplate: "RAG 987F",
  },
]

export const companies = [
  { id: 1, name: "Toyota", car_company: "Toyota" },
  { id: 2, name: "Swift Bus", car_company: "Nissan" },
  { id: 3, name: "City Connect", car_company: "Hyundai" },
  { id: 4, name: "Rural Link", car_company: "Mitsubishi" },
  { id: 5, name: "Airport Shuttle", car_company: "Kia" },
  { id: 6, name: "Metro Bus", car_company: "Isuzu" },
]
