"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

export type Language = "en" | "rw" | "fr"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header
    appName: "Cavgo",
    tagline: "Your journey starts here",
    signIn: "Sign In",
    signOut: "Sign Out",
    myTickets: "My Tickets",

    // Search
    searchRoutes: "Search Routes",
    from: "From",
    to: "To",
    originPlaceholder: "Origin city or stop",
    destinationPlaceholder: "Destination city or stop",
    companyPlaceholder: "Type company name...",
    selectCompany: "Select company",
    allCompanies: "All companies",
    departedCityRoutes: "City Routes",
    ruralRoutes: "Provincial Routes",
    searchButton: "Search Routes",
    reset: "Reset",
    filtersActive: "filters active",
    filter: "filter",
    transportationCompany: "Transportation Company",
    routeFilters: "Route Filters",

    // Route Cards
    seatsAvailable: "seats available",
    bookNow: "Book Now",
    notAvailable: "Not Available",
    fromPrice: "from",
    enRouteTo: "En route to",
    remaining: "remaining",
    routeStops: "Route Stops",
    ruralRouteProgress: "Provincial route in progress: Limited booking options available",
    timeTBD: "Time TBD",

    // Booking Modal
    bookYourJourney: "Book Your Journey",
    journeyDetails: "Journey Details",
    selectOrigin: "Select origin",
    selectDestination: "Select destination",
    numberOfSeats: "Number of Seats",
    seat: "seat",
    seats: "seats",
    available: "Available",
    selectStopsAndSeatsForPrice: "Select stops and seats to see price",
    phonePlaceholder: "+250 xxx xxx xxx",
    phoneUsageNote: "This will be used for payments and notifications about the journey",
    ruralRouteRules: "Provincial Route Rules",
    ruralScheduledRule: "Boarding only from origin. All destinations available for booking.",
    ruralDepartedRule: "Limited to next available stop or final destination only.",
    upcomingBoardingPoints: "Upcoming Boarding Points",
    futureBoardingPoints: "Future Boarding Points",
    upcomingBoardingMessage: "These stops will become available for booking as the bus reaches them:",
    nextBoardingMessage: "Next stop that will become available for boarding:",
    nextAvailable: "next available",
    futureBoardingMessage: "These stops will become available for booking once the route starts:",
    cityRoute: "City Route",
    cityRouteRule: "You can book to any unpassed stop for maximum flexibility.",
    noProvincialBookingPoints: "No Booking Points Available",
    noCityBookingPoints: "No Available Stops",
    finalDestinationOnly: "The bus has reached its final destination or only the final destination is remaining.",
    passengerInformation: "Passenger Information",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    phoneNumber: "Phone Number",
    email: "Email (Optional)",
    paymentInformation: "Payment Information",
    mobileMoneyNumber: "Mobile Money Number",
    paymentPrompt: "Payment will be processed via Mobile Money. You'll receive a payment prompt on this number.",
    registeredPhoneNote: "Using your registered phone number. You can change it above if needed.",
    priceSummary: "Price Summary",
    pricePerSeat: "Price per seat:",
    totalLabel: "Total:",
    cancel: "Cancel",
    processing: "Processing...",
    bookFor: "Book for",

    // Booking Confirmation
    bookingConfirmed: "Booking Confirmed!",
    bookingConfirmedMessage: "Your booking has been confirmed",
    bookingReference: "Booking reference:",
    route: "Route:",
    close: "Close",
    viewTicket: "View Ticket",
    confirmBooking: "Confirm Booking",
    pleaseConfirmBookingDetails: "Please confirm your booking details",
    company: "Company",
    trip: "Trip",
    pickupTime: "Pickup Time",
    carPlate: "Car Plate",
    confirmAndBook: "Confirm & Book",
    bookingFailed: "Booking Failed",
    somethingWentWrong: "Something went wrong",
    paymentPending: "Payment Pending",
    bookingPendingPaymentMessage: "Your booking is pending payment confirmation",
    paymentInstructionsTitle: "Payment Instructions",
    paymentInstructionsMessage: "You will receive a mobile money payment prompt shortly. Please complete the payment.",
    pleaseSaveYourTickets: "Please Save Your Tickets!",
    saveTicketsWarning: "You are not signed in. Make sure to download and save your tickets before closing this window.",
    generatingPDF: "Generating PDF...",
    downloadTicketsPDF: "Download Tickets (PDF)",
    yourTickets: "Your Tickets",
    ticketNumber: "Ticket Number",
    pickup: "Pickup",
    dropoff: "Dropoff",
    departureTime: "Departure Time",
    estimatedPickupTime: "Estimated Pickup Time",
    notifyWhenCarCloseToPickup: "You'll be notified when the vehicle is close to your pickup point",
    origin: "Origin",
    destination: "Destination",
    stop: "Stop",

    // Auth Modal
    signInTitle: "Sign In",
    password: "Password",
    enterPassword: "Enter your password",
    invalidCredentials: "Invalid email or password",
    demoCredentials: "Demo credentials:",
    anyPassword: "Password: any password",
    signingIn: "Signing in...",

    // Tickets
    myTicketsTitle: "My Tickets",
    noTickets: "No tickets found",
    noTicketsMessage: "You haven't booked any routes yet.",
    ticketDetails: "Ticket Details",
    passenger: "Passenger:",
    contact: "Contact:",
    departure: "Departure:",
    arrival: "Arrival:",
    ticketReference: "Ticket Reference:",
    paymentStatus: "Payment Status:",
    paid: "Paid",
    pending: "Pending",
    download: "Download",
    share: "Share",

    // General
    noRoutesFound: "No routes found",
    tryAdjusting: "Try adjusting your search criteria",
    currentFilters: "Current filters:",
    companies: "Companies",
    destinations: "destinations",
    routes: "routes",
    routesIn: "routes in",
    footer: "Making travel accessible for everyone.",
  },
  rw: {
    // Header
    appName: "CAVGO",
    tagline: "Ingendo zigera kuri bose zitangirira hano",
    signIn: "Kwinjira",
    signOut: "Gusohoka",
    myTickets: "Amatike Yanjye",
    // Search
    searchRoutes: "Shakisha ingendo",
    from: "Aho uhagurukira",
    to: "Aho ugana",
    originPlaceholder: "Aho uhagurukira",
    destinationPlaceholder: "Aho ugana",
    companyPlaceholder: "Andika izina ry'isosiyeti",
    selectCompany: "Hitamo isosiyeti",
    allCompanies: "Amasosiyeti yose",
    departedCityRoutes: "Inzira zo mu mijyi",
    ruralRoutes: "Inzira zijya mu ntara",
    searchButton: "Shakisha ingendo",
    reset: "Bikuremo",
    filtersActive: "Ingendo zihari",
    filter: "Robanura",
    transportationCompany: "Isosiyeti z'ubwikorezi",
    routeFilters: "Isosiyeti ziri gukora",
    // Route Cards
    seatsAvailable: "Imyanya isigaye",
    bookNow: "Tega",
    notAvailable: "Ntabwo ruhari",
    fromPrice: "Aho ihagurukira",
    enRouteTo: "Aho igana",
    remaining: "Ibisigaye",
    routeStops: "Aho imodoka ihagarara",
    ruralRouteProgress: "Ingendo zijya mu ntara zirakomeza kandi amahitamo ni menshi",
    timeTBD: "Igihe Kitazwi",
    // Booking Modal
    bookYourJourney: "Tangira wikatire itike",
    journeyDetails: "Amakuru y'Urugendo",
    selectOrigin: "Hitamo aho ufatira imodoka",
    selectDestination: "Hitamo aho ugana",
    numberOfSeats: "Umubare w'imyanya",
    seat: "umwanya",
    seats: "Imyanya",
    available: "Urahari",
    selectStopsAndSeatsForPrice: "Hitamo aho uhagarara n'imyanya kugira ngo ubone igiciro",
    phonePlaceholder: "+250 xxx xxx xxx",
    phoneUsageNote: "Ibi bizakoreshwa mu kwishyura no kubamenyesha urugendo",
    ruralRouteRules: "Imihanda ijya muntara",
    ruralScheduledRule: "Fatira imodoka aho uturuka hose. Amerekezo yose arimo ku bwanyu",
    ruralDepartedRule: "Ibyapa imodoka itarageraho niyo bitegerwaho bigana aho ugana.",
    upcomingBoardingPoints: "ibyapa imodoka igiye gukurikizaho",
    futureBoardingPoints: "Ibyapa by'ahazaza",
    upcomingBoardingMessage: "ibyapa bitegerwaho iyo imodoka iri hafi kubigeraho:",
    nextBoardingMessage: "Icyapa gikurikiraho kikanakatirwaho itike:",
    nextAvailable: "Icyapa gikurikira",
    futureBoardingMessage: "Ibi byapa byemera ko babitegeraho igihe imodoka itangiye urugendo:",
    cityRoute: "urugendo rwo mu mujyi",
    cityRouteRule: "Ushobora kwikatira itike ku cyapa imodoka itararenga.",
    noProvincialBookingPoints: "Nta Hantu ho gutegeraho hahari",
    noCityBookingPoints: "Nta Hantu Hahari",
    finalDestinationOnly: "Imodoka yarangije urugendo cyangwa hasigaye aho igarukira gusa.",
    passengerInformation: "Amakuru y'Umugenzi",
    fullName: "Amazina yose",
    enterFullName: "Andika amazina yawe yose",
    phoneNumber: "Nimero ya telefoni",
    email: "Imeyili (amahitamo)",
    paymentInformation: "Amakuru yo Kwishyura",
    mobileMoneyNumber: "Nimero ya Mobile Money",
    paymentPrompt: "Kwishyura biri gutunganywa binyuze kuri M-Money. Itegure kwishyura ukoresheje iyi nimero ya telephone.",
    registeredPhoneNote: "Ishyura ukoresheje indi nimero niba ntamafaranga ahagije ufite kuri nimero ikubaruyeho. Bihindurire hejuru.",
    priceSummary: "Incamake y'Igiciro",
    pricePerSeat: "Igiciro ku mugenzi umwe:",
    totalLabel: "Igiteranyo:",
    cancel: "Hagarika",
    processing: "Tegereza",
    bookFor: "Tega kuri",
    // Booking Confirmation
    bookingConfirmed: "Gutega byemejwe!",
    bookingConfirmedMessage: "Kwikatira itike byemejwe",
    bookingReference: "Ijambo banga ry'itike:",
    route: "Inzira:",
    close: "Gufunga",
    viewTicket: "Reba Itike",
    confirmBooking: "Emeza Kubuka",
    pleaseConfirmBookingDetails: "Nyamuneka emeza amakuru yawe yo kubuka",
    company: "Ikigo",
    trip: "Urugendo",
    pickupTime: "Igihe cyo Gutangira",
    carPlate: "Plake y'Imodoka",
    confirmAndBook: "Emeza & Buka",
    bookingFailed: "Kubuka Byanze",
    somethingWentWrong: "Habayeho ikibazo",
    paymentPending: "Kwishyura Gutegereje",
    bookingPendingPaymentMessage: "Kubuka kwawe gutegereje kwemezwa kw'amafaranga",
    paymentInstructionsTitle: "Amabwiriza yo Kwishyura",
    paymentInstructionsMessage: "Uzakira ubutumwa bwo kwishyura kuri mobile money vuba. Nyamuneka uzuza kwishyura.",
    pleaseSaveYourTickets: "Nyamuneka Bika Amatike Yawe!",
    saveTicketsWarning: "Ntiwinjiye. Menya ko wakuramo kandi ubike amatike yawe mbere yo gufunga idirishya.",
    generatingPDF: "Gukora PDF...",
    downloadTicketsPDF: "Kuramo Amatike (PDF)",
    yourTickets: "Amatike Yawe",
    ticketNumber: "Nimero y'Itike",
    pickup: "Aho Utangirira",
    dropoff: "Aho Umanukira",
    departureTime: "Igihe cyo Gutaha",
    estimatedPickupTime: "Igihe Cyagenwe cyo Gutangira",
    notifyWhenCarCloseToPickup: "Uzabimenyeshwa iyo imodoka igeze hafi y'aho utangirira",
    origin: "Intangiriro",
    destination: "Intego",
    stop: "Guhagarara",
    // Auth Modal
    signInTitle: "Kwinjira",
    password: "Ijambo banga",
    enterPassword: "Andika ijambo ry'ibanga",
    invalidCredentials: "Imeyili cyangwa ijambo ryibanga bitari byo",
    demoCredentials: "Amakuru yo kugerageza:",
    anyPassword: "Ijambo ryibanga: ijambo iryo ari ryo ryose",
    signingIn: "Kwinjira...",
    // Tickets
    myTicketsTitle: "Amatike Yanjye",
    noTickets: "Nta matike aboneka",
    noTicketsMessage: "Nta rugendo rubonetse.",
    ticketDetails: "Amakuru y'Itike",
    passenger: "Umugenzi:",
    contact: "Duhamagare:",
    departure: "Gutangira urugendo:",
    arrival: "Kugera:",
    ticketReference: "Nimero y'Itike:",
    paymentStatus: "Ubwishyu:",
    paid: "Yishyuwe",
    pending: "Ntirishyurwa",
    download: "Bika itike",
    share: "Sangiza",
    // General
    noRoutesFound: "Nta nzira zaboneka",
    tryAdjusting: "Gerageza guhindura ibyo ushakisha",
    currentFilters: "Ingendo zihari:",
    companies: "Amasosiyeti",
    destinations: "Aho yerekeza",
    routes: "inzira",
    routesIn: "inzira muri",
    footer: "Dutuma ingendo zigera kuri bose.",
  },
  fr: {
    // Header
    appName: "Cavgo",
    tagline: "Votre voyage commence ici",
    signIn: "Se connecter",
    signOut: "Se déconnecter",
    myTickets: "Mes Billets",

    // Search
    searchRoutes: "Rechercher des Itinéraires",
    from: "De",
    to: "À",
    originPlaceholder: "Ville ou arrêt de départ",
    destinationPlaceholder: "Ville ou arrêt de destination",
    companyPlaceholder: "Tapez le nom de la compagnie...",
    selectCompany: "Sélectionner une compagnie",
    allCompanies: "Toutes les compagnies",
    departedCityRoutes: "Itinéraires Urbains Partis",
    ruralRoutes: "Itinéraires Provinciaux",
    searchButton: "Rechercher des Itinéraires",
    reset: "Réinitialiser",
    filtersActive: "filtres actifs",
    filter: "filtre",
    transportationCompany: "Compagnie de Transport",
    routeFilters: "Filtres d'Itinéraires",

    // Route Cards
    seatsAvailable: "sièges disponibles",
    bookNow: "Réserver Maintenant",
    notAvailable: "Non Disponible",
    fromPrice: "à partir de",
    enRouteTo: "En route vers",
    remaining: "restant",
    routeStops: "Arrêts de l'Itinéraire",
    ruralRouteProgress: "Itinéraire provincial en cours: Options de réservation limitées disponibles",
    timeTBD: "Heure à déterminer",

    // Booking Modal
    bookYourJourney: "Réservez Votre Voyage",
    journeyDetails: "Détails du Voyage",
    selectOrigin: "Sélectionner l'origine",
    selectDestination: "Sélectionner la destination",
    numberOfSeats: "Nombre de Sièges",
    seat: "siège",
    seats: "sièges",
    available: "Disponible",
    selectStopsAndSeatsForPrice: "Sélectionnez les arrêts et les sièges pour voir le prix",
    phonePlaceholder: "+250 xxx xxx xxx",
    phoneUsageNote: "Ceci sera utilisé pour les paiements et les notifications concernant le voyage",
    ruralRouteRules: "Règles des Itinéraires Provinciaux",
    ruralScheduledRule: "Embarquement uniquement depuis l'origine. Toutes les destinations disponibles.",
    ruralDepartedRule: "Limité au prochain arrêt disponible ou à la destination finale uniquement.",
    upcomingBoardingPoints: "Points d'Embarquement à Venir",
    futureBoardingPoints: "Points d'Embarquement Futurs",
    upcomingBoardingMessage: "Ces arrêts seront disponibles lorsque le bus les atteindra :",
    nextBoardingMessage: "Prochain arrêt qui sera disponible pour l'embarquement :",
    nextAvailable: "prochain disponible",
    futureBoardingMessage: "Ces arrêts seront disponibles une fois l'itinéraire commencé :",
    cityRoute: "Itinéraire Urbain",
    cityRouteRule: "Vous pouvez réserver vers n'importe quel arrêt non passé pour une flexibilité maximale.",
    noProvincialBookingPoints: "Aucun Point de Réservation Disponible",
    noCityBookingPoints: "Aucun Arrêt Disponible",
    finalDestinationOnly: "Le bus a atteint sa destination finale ou seule la destination finale reste.",
    passengerInformation: "Informations du Passager",
    fullName: "Nom Complet",
    enterFullName: "Entrez votre nom complet",
    phoneNumber: "Numéro de Téléphone",
    email: "Email (Optionnel)",
    paymentInformation: "Informations de Paiement",
    mobileMoneyNumber: "Numéro Mobile Money",
    paymentPrompt: "Le paiement sera traité via Mobile Money. Vous recevrez une invite de paiement sur ce numéro.",
    registeredPhoneNote:
      "Utilisation de votre numéro de téléphone enregistré. Vous pouvez le modifier ci-dessus si nécessaire.",
    priceSummary: "Résumé des Prix",
    pricePerSeat: "Prix par siège:",
    totalLabel: "Total:",
    cancel: "Annuler",
    processing: "Traitement...",
    bookFor: "Réserver pour",

    // Booking Confirmation
    bookingConfirmed: "Réservation Confirmée!",
    bookingConfirmedMessage: "Votre réservation a été confirmée",
    bookingReference: "Référence de réservation:",
    route: "Itinéraire:",
    close: "Fermer",
    viewTicket: "Voir le Billet",
    confirmBooking: "Confirmer la Réservation",
    pleaseConfirmBookingDetails: "Veuillez confirmer les détails de votre réservation",
    company: "Compagnie",
    trip: "Voyage",
    pickupTime: "Heure de Prise en Charge",
    carPlate: "Plaque d'Immatriculation",
    confirmAndBook: "Confirmer & Réserver",
    bookingFailed: "Échec de la Réservation",
    somethingWentWrong: "Quelque chose s'est mal passé",
    paymentPending: "Paiement en Attente",
    bookingPendingPaymentMessage: "Votre réservation est en attente de confirmation de paiement",
    paymentInstructionsTitle: "Instructions de Paiement",
    paymentInstructionsMessage: "Vous recevrez sous peu une demande de paiement par mobile money. Veuillez compléter le paiement.",
    pleaseSaveYourTickets: "Veuillez Sauvegarder Vos Billets!",
    saveTicketsWarning: "Vous n'êtes pas connecté. Assurez-vous de télécharger et sauvegarder vos billets avant de fermer cette fenêtre.",
    generatingPDF: "Génération du PDF...",
    downloadTicketsPDF: "Télécharger les Billets (PDF)",
    yourTickets: "Vos Billets",
    ticketNumber: "Numéro de Billet",
    pickup: "Prise en Charge",
    dropoff: "Dépose",
    departureTime: "Heure de Départ",
    estimatedPickupTime: "Heure Estimée de Prise en Charge",
    notifyWhenCarCloseToPickup: "Vous serez notifié lorsque le véhicule sera proche de votre point de prise en charge",
    origin: "Origine",
    destination: "Destination",
    stop: "Arrêt",

    // Auth Modal
    signInTitle: "Se Connecter",
    password: "Mot de Passe",
    enterPassword: "Entrez votre mot de passe",
    invalidCredentials: "Email ou mot de passe invalide",
    demoCredentials: "Identifiants de démonstration:",
    anyPassword: "Mot de passe: n'importe quel mot de passe",
    signingIn: "Connexion...",

    // Tickets
    myTicketsTitle: "Mes Billets",
    noTickets: "Aucun billet trouvé",
    noTicketsMessage: "Vous n'avez encore réservé aucun itinéraire.",
    ticketDetails: "Détails du Billet",
    passenger: "Passager:",
    contact: "Contact:",
    departure: "Départ:",
    arrival: "Arrivée:",
    ticketReference: "Référence du Billet:",
    paymentStatus: "Statut du Paiement:",
    paid: "Payé",
    pending: "En Attente",
    download: "Télécharger",
    share: "Partager",

    // General
    noRoutesFound: "Aucun itinéraire trouvé",
    tryAdjusting: "Essayez d'ajuster vos critères de recherche",
    currentFilters: "Filtres actuels:",
    companies: "Compagnies",
    destinations: "destinations",
    routes: "itinéraires",
    routesIn: "itinéraires dans",
    footer: "Rendre les voyages accessibles à tous.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const storedLanguage = localStorage.getItem("language") as Language
    if (storedLanguage && ["en", "rw", "fr"].includes(storedLanguage)) {
      setLanguage(storedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
